### ISSUE TITLE
root-me Challenge 4

### ISSUE THREAD

**Issue by decker78** [jeremybeaume/root-me#1]
Hello Jeremy,

Does your solution for root-me challenge 4 works? I'm completely stuck for days and I cannot seem to figure out how to get the shell. 

Any help welcome.

http://stackoverflow.com/questions/41068485/buffer-overflow-using-environment-variable-linux-gdb

Best Regards
Bart

**Comment by jeremybeaume** [comment]
Hey !

So I've been thinking about you =)
I remember having spend a lot of time on this one too, although it is quite
simple in fact.

Of course the buffer overflow is in the strcpy in the GetEnv function
provided. Never use strcpy .....
Using this, you can overwrite the EIP stored in stack when GetEnv has been
called.
This will allow you to make the execution flow jump wherever you want, and
why not over a shell code ?

I don't remember exactly what I did on this one, and I'm not even sure what
I have stored on github works, that's just there because I worked on 2
computers. So don't really bother reading my stuff.

From what I remember, I used the USERNAME variable just so it is more
convenient : messing with PATH makes your shell unable to find common
commands. So my USERNAME variable has to hold the shellcode, and then junk,
and be long enough to rewrite EIP at the end.

So it's most probably going to be 128 (USERNAME) + 128 (SHELL) + 128 (PATH)
+ 8 (EBP + EIP) long.
Shell code is in USERNAME, 128B long max. Then the 256B of data written
over SHELL & PATH are pointless, as they will be erased just after. But you
buffer is long enough to write over the stored EIP, and so, at the end of
GetEnv, you can make the processor jump on the USERNAME address, where your
shellcode is stored.

SHELL_CODE (128) | JUNK (128 over SHELL) | JUNK (128 over PATH) | EBP | EIP
(=&SHELL_CODE)

Be VERY VERY carefull when testing : gdb messes up with env variables
(adding some, removing others, ...), and so, what works on your computer,
on gdb, will not work on the final server, you'll have to check variable
alignment, which is a pain in the ass, absolutely ! =)

That should get you going =)

Jérémy Beaume

Network Security Engineer

2016-12-11 12:43 GMT+01:00 decker78 <notifications@github.com>:

**Comment by decker78** [comment]
As mailed this was solved. Thanks again for your support!
